#Flutter Wrapper
-keep class io.flutter.app.** { *; }
-keep class io.flutter.plugin.**  { *; }
-keep class io.flutter.util.**  { *; }
-keep class io.flutter.view.**  { *; }
-keep class io.flutter.**  { *; }
-keep class io.flutter.plugins.**  { *; }
-keep class com.example.flutterapp.** { *; }
-keep class com.facebook.jni.** { *; }
-keep class org.pytorch.** { *; }
-ignorewarnings